### ISSUE TITLE
investigate storage option

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-explore#1]
bcolz or pytables (HDF5). bcolz appears more performant.

http://nbviewer.ipython.org/github/Blosc/movielens-bench/blob/master/querying-ep14.ipynb

**Comment by ntrrgc** [comment]
At the moment I use one file per independent variable. Since server querying is only made on this variable, this provides the best performance.

Server maintenance is also quite simple, adding a new submission is a matter of running a command (which hopefully can be hooked in HEPData without too much trouble) and then data files are served as static files, which again puts as little stress on the server as possible.

As long as we keep with this model there is nothing to gain from using a more complex storage solution.
