### ISSUE TITLE
counts appear to be wrong

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-explore#7]
e.g. http://hepdata.rufian.eu/#e4vhR

See here, there are 2.5k points for -T (GEV**2) in the independent variables list, but the count in the first plot is 2930.

<img width="1403" alt="screen shot 2016-05-26 at 13 39 04" src="https://cloud.githubusercontent.com/assets/282396/15573416/3cb94414-2347-11e6-9f53-f8dfcbc71dfe.png">

On a similar note, why are the other plots, with THETA (DEG) shown? -T (GEV doesn't seem to exist in these).

**Comment by ntrrgc** [comment]
The numbers on the left represent tables, not data points. I have added a label to make that explicit.

![](http://i.imgur.com/U4wvNkg.png)

**Comment by ntrrgc** [comment]
> On a similar note, why are the other plots, with THETA (DEG) shown? -T (GEV doesn't seem to exist in these).

You are searching for tables having an independent variable named `-T(GEV**2)`, but some tables may have several more independent variables. They get plotted too.

For instance, here is a table having both `-T(GEV**2)` and `THETA (DEG)`: https://hepdata.net/record/ins5159?table=Table8

You can use the new _View publications_ button to find these.

**Comment by eamonnmag** [comment]
Thanks for the clarification. Even so, in the header part, the counts still don't match. It says 216 tables found in 100 publications.

On the second point, I think that if you just search for Theta (DEG) for instance, you should only see that, otherwise it could be confusing. Or we should mark the plots differently. Comments welcome from @GraemeWatt  @cranmer and @lukasheinrich

**Comment by ntrrgc** [comment]
> Thanks for the clarification. Even so, in the header part, the counts still don't match. It says 216 tables found in 100 publications.

There is a hard limit on how many publications can be fetched in a single search (it currently is set at 100 publications). Otherwise the empty filter would have to download all HEPData.

**Comment by ntrrgc** [comment]
I'm removing the bug label since this was by design.

A message indicating the fact (e.g. "some results omitted") should be added though.

**Comment by ntrrgc** [comment]
I've added such message in c651a07258311cc6e624ae7ec47bb33b295b30ed.

![](http://i.imgur.com/9wnHV7J.png)

**Comment by ntrrgc** [comment]
If the 100 publications limit is too low, I can raise it.

As a fun fact, I tried completely removing the limit and searching without filters (i.e. retrieve all\* HEPData). 

It takes half a minute loading, but it completes and works relatively well after, using only 8 MiB of gzipped transfer that expand to 73 MiB unzipped and < 700 MiB of RAM once indexed with plots... which is quite amazing compared to the previous implementation with crossfilter that used > 1.5 GiB with big subsets of the data.

\* There are missing publications in HEPData Explore due to the fact that some could not be decoded successfully due to issues parsing their submission files (e.g. free text inside tables). The `record_aggregator` program shows how many (~5%), which ones and why.
